defaults:
  - _self_
  - experiment: ${experiment}
  - override hydra/job_logging: disabled

model:
  model_name_or_path: "unsloth/Meta-Llama-3.1-8B"
  max_seq_length: 2048
  load_in_4bit: true
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0.0

data:
  dataset_path: "/afs/cs.stanford.edu/u/vvajipey/research/continual/gisting/data/alpaca_plus"
  max_train_samples: null
  max_eval_samples: null

training:
  output_dir: "/afs/cs.stanford.edu/u/vvajipey/research/continual/project/outputs"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.03
  logging_steps: 10
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  seed: 42
  remove_unused_columns: false
  bf16: true
  gradient_checkpointing: true
  max_grad_norm: 0.3
  lr_scheduler_type: "cosine"
  optim: "paged_adamw_32bit"
  do_eval: true
  do_train: true
  report_to: "none"
  save_total_limit: 2
