_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 4
device:
    value: cuda
eval_interval:
    value: 50
learning_rate:
    value: 0.0001
lora_rank:
    value: 4
max_length:
    value: 512
model_name_or_path:
    value: meta-llama/llama-3.2-1B
num_epochs:
    value: 3
wandb_project:
    value: lora-compression-head
